### ISSUE TITLE
ANNTrain tr = new ANNTrain();     	tr.annMain();

### ISSUE THREAD

**Issue by liycode** [fan-wenjie/EasyPR-Java#7]
ANNTrain tr = new ANNTrain();
tr.annMain();

报错：

 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000057f0bfe3, pid=1552, tid=3620

JRE version: Java(TM) SE Runtime Environment (7.0_71-b14) (build 1.7.0_71-b14)
Java VM: Java HotSpot(TM) 64-Bit Server VM (24.71-b01 mixed mode windows-amd64 compressed oops)
Problematic frame:
C  [msvcr100.dll+0x3bfe3]

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
 An error report file with more information is saved as:
 E:\EasyPR-Java-master\hs_err_pid1552.log

If you would like to submit a bug report, please visit:
http://bugreport.sun.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

**Comment by numen06** [comment]
我也遇到了，这个问题，怎么解决？

**Comment by tpglzu** [comment]
@liycode @numen06 两位的问题有没有解决？我也遇到了同样的问题。。。

**Comment by tpglzu** [comment]
@fan-wenjie 我对代码做了以下调整，基本上能够进行训练。但还有其他问题，希望能多多指教
- `saveTrainData`中调用`features`的代码，改为调用`CoreFunc.features`  
  _效果：`saveTrainData`中`trainingData`和`classes`生产成功_  
  _问题：执行`ann_data.xml保存`时失败_
- 不执行`ann_data.xml保存`，`saveTrainData`中`trainingData`和`classes`准备完了之后，直接调用`annTrain`进行训练  
  _效果：训练成功执行，直接使用训练后的模型进行预测，预测成功_  
  _问题：保存模型`ann.xml`时失败，`ann.xml`可以生成，但生成的XML文件中标签有错误_

**Comment by hbking2000** [comment]
svm训练都传什么参数呀
